/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ClientCtr;
import javax.swing.JPanel;

/**
 *
 * @author hoang
 */
public class ClientMainFrm extends javax.swing.JFrame {
    private ClientCtr myControl;
    /**
     * Creates new form ClientMainFrm
     */
    public ClientMainFrm(ClientCtr control) {
        initComponents();
        myControl = control;
        tblPanel.add("Home",new HomeFrm());
        this.setTitle("Game Mario");
        this.setLocationRelativeTo(null);
    }

    public void setPanel(JPanel panel, String title){
        tblPanel.removeAll();
        tblPanel.add(title, panel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        btnSearchUser = new javax.swing.JButton();
        btnFriends = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnGroups = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        tblPanel = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSystem = new javax.swing.JMenu();
        itemHome = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemEditInf = new javax.swing.JMenuItem();
        itemSearchUser = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemExit = new javax.swing.JMenuItem();
        menuFriends = new javax.swing.JMenu();
        itemSeeFriends = new javax.swing.JMenuItem();
        itemRequest = new javax.swing.JMenuItem();
        menuGroup = new javax.swing.JMenu();
        itemSeeGroups = new javax.swing.JMenuItem();
        itemJoinGroup = new javax.swing.JMenuItem();
        menuRank = new javax.swing.JMenu();
        itemSeeRanking = new javax.swing.JMenuItem();
        menuTournament = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnHome.setText("Home");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHome);

        btnSearchUser.setText("Search User");
        btnSearchUser.setFocusable(false);
        btnSearchUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchUser.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnSearchUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSearchUser);

        btnFriends.setText("Friends");
        btnFriends.setFocusable(false);
        btnFriends.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFriends.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnFriends.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriendsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFriends);

        btnRanking.setText("Ranking");
        btnRanking.setFocusable(false);
        btnRanking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRanking.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnRanking.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRanking);

        btnGroups.setText("Groups");
        btnGroups.setFocusable(false);
        btnGroups.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGroups.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnGroups.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGroups);

        btnLogout.setText("Logout");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setMargin(new java.awt.Insets(10, 14, 10, 14));
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        menuSystem.setText("System");

        itemHome.setText("Home");
        itemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHomeActionPerformed(evt);
            }
        });
        menuSystem.add(itemHome);
        menuSystem.add(jSeparator2);

        itemEditInf.setText("Edit information");
        itemEditInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditInfActionPerformed(evt);
            }
        });
        menuSystem.add(itemEditInf);

        itemSearchUser.setText("Search user");
        itemSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchUserActionPerformed(evt);
            }
        });
        menuSystem.add(itemSearchUser);

        itemLogout.setText("Logout");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        menuSystem.add(itemLogout);
        menuSystem.add(jSeparator1);

        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        menuSystem.add(itemExit);

        jMenuBar1.add(menuSystem);

        menuFriends.setText("Friends");

        itemSeeFriends.setText("See Friends");
        itemSeeFriends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeeFriendsActionPerformed(evt);
            }
        });
        menuFriends.add(itemSeeFriends);

        itemRequest.setText("Request Friends");
        itemRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRequestActionPerformed(evt);
            }
        });
        menuFriends.add(itemRequest);

        jMenuBar1.add(menuFriends);

        menuGroup.setText("Group");

        itemSeeGroups.setText("See Groups");
        itemSeeGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeeGroupsActionPerformed(evt);
            }
        });
        menuGroup.add(itemSeeGroups);

        itemJoinGroup.setText("Join Group");
        itemJoinGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJoinGroupActionPerformed(evt);
            }
        });
        menuGroup.add(itemJoinGroup);

        jMenuBar1.add(menuGroup);

        menuRank.setText("Rank");

        itemSeeRanking.setText("See Ranking");
        itemSeeRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeeRankingActionPerformed(evt);
            }
        });
        menuRank.add(itemSeeRanking);

        jMenuBar1.add(menuRank);

        menuTournament.setText("Tournament");
        jMenuBar1.add(menuTournament);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tblPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        // TODO add your handling code here:
        myControl.closeConnection();
        new LoginFrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        myControl.closeConnection();
        new LoginFrm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_itemExitActionPerformed

    private void itemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHomeActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Home", new HomeFrm());
    }//GEN-LAST:event_itemHomeActionPerformed

    private void itemEditInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditInfActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Edit information", new EditInformationFrm(myControl));
    }//GEN-LAST:event_itemEditInfActionPerformed

    private void itemSeeFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeeFriendsActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Friends", new ListFriendFrm(myControl));
    }//GEN-LAST:event_itemSeeFriendsActionPerformed

    private void itemSeeRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeeRankingActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Ranking", new RankFrm(myControl));
    }//GEN-LAST:event_itemSeeRankingActionPerformed

    private void itemSeeGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeeGroupsActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Groups", new GroupFrm(myControl));
    }//GEN-LAST:event_itemSeeGroupsActionPerformed

    private void itemSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSearchUserActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Search Player",new SearchUserFrm(myControl));
    }//GEN-LAST:event_itemSearchUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Home",new HomeFrm());
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Search Player",new SearchUserFrm(myControl));
    }//GEN-LAST:event_btnSearchUserActionPerformed

    private void btnFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriendsActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Friends", new ListFriendFrm(myControl));
    }//GEN-LAST:event_btnFriendsActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Ranking", new RankFrm(myControl));
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupsActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Groups", new GroupFrm(myControl));
    }//GEN-LAST:event_btnGroupsActionPerformed

    private void itemRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRequestActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Request friends", new RequestFriendFrm(myControl));
    }//GEN-LAST:event_itemRequestActionPerformed

    private void itemJoinGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJoinGroupActionPerformed
        // TODO add your handling code here:
        tblPanel.removeAll();
        tblPanel.add("Search group", new JoinGroupFrm(myControl));
    }//GEN-LAST:event_itemJoinGroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFriends;
    private javax.swing.JButton btnGroups;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JMenuItem itemEditInf;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemHome;
    private javax.swing.JMenuItem itemJoinGroup;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuItem itemRequest;
    private javax.swing.JMenuItem itemSearchUser;
    private javax.swing.JMenuItem itemSeeFriends;
    private javax.swing.JMenuItem itemSeeGroups;
    private javax.swing.JMenuItem itemSeeRanking;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuFriends;
    private javax.swing.JMenu menuGroup;
    private javax.swing.JMenu menuRank;
    private javax.swing.JMenu menuSystem;
    private javax.swing.JMenu menuTournament;
    private javax.swing.JTabbedPane tblPanel;
    // End of variables declaration//GEN-END:variables
}
