/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ClientCtr;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JFrame;
import model.Game;
import model.ObjectWrapper;
import model.User;
import model.Character;

/**
 *
 * @author hoang
 */
public class GameMarioFrm extends javax.swing.JFrame {
    private Socket mySocket;
    private Game myGame;
    private User myUser;
    /**
     * Creates new form GameMarioFrm
     */
    public GameMarioFrm(Socket socket,Game game, User user) {
        initComponents();
        this.setTitle(user.getName());
        this.mySocket = socket;
        this.myGame = game;
        this.myUser = user;
        this.pack();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMario = new javax.swing.JButton();
        btnPeach = new javax.swing.JButton();
        btnYoshi = new javax.swing.JButton();
        btnDaisy = new javax.swing.JButton();
        btnToad = new javax.swing.JButton();
        btnToadette = new javax.swing.JButton();
        btnBowser = new javax.swing.JButton();
        btnDonkeyKong = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Game Mario");

        btnMario.setBackground(new java.awt.Color(255, 255, 255));
        btnMario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mario.png"))); // NOI18N
        btnMario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarioActionPerformed(evt);
            }
        });

        btnPeach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/peach.png"))); // NOI18N
        btnPeach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPeach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeach.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeachActionPerformed(evt);
            }
        });

        btnYoshi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yoshi.png"))); // NOI18N
        btnYoshi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnYoshi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnYoshi.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnYoshi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoshiActionPerformed(evt);
            }
        });

        btnDaisy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/daisy.png"))); // NOI18N
        btnDaisy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaisy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDaisy.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDaisy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaisyActionPerformed(evt);
            }
        });

        btnToad.setBackground(new java.awt.Color(255, 255, 255));
        btnToad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/toad.png"))); // NOI18N
        btnToad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToad.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnToad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToadActionPerformed(evt);
            }
        });

        btnToadette.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/toadette.png"))); // NOI18N
        btnToadette.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToadette.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToadette.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnToadette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToadetteActionPerformed(evt);
            }
        });

        btnBowser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bowser.png"))); // NOI18N
        btnBowser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBowser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBowser.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBowserActionPerformed(evt);
            }
        });

        btnDonkeyKong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/donkeykong.png"))); // NOI18N
        btnDonkeyKong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonkeyKong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDonkeyKong.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnDonkeyKong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonkeyKongActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please choose your character");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnToad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnToadette, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
                                .addGap(23, 23, 23)
                                .addComponent(btnBowser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDonkeyKong, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPeach, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
                                .addGap(23, 23, 23)
                                .addComponent(btnYoshi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDaisy, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDaisy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnYoshi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnPeach, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnMario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnToad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnToadette, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnBowser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnDonkeyKong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarioActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Mario", "mario.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMarioActionPerformed

    private void btnPeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeachActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Peach", "peach.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPeachActionPerformed

    private void btnYoshiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoshiActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Yoshi", "yoshi.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnYoshiActionPerformed

    private void btnDaisyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaisyActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Daisy", "daisy.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDaisyActionPerformed

    private void btnToadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToadActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Toad", "toad.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnToadActionPerformed

    private void btnToadetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToadetteActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Toadette", "toadette.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnToadetteActionPerformed

    private void btnBowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBowserActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Bowser", "bowser.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBowserActionPerformed

    private void btnDonkeyKongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonkeyKongActionPerformed
        // TODO add your handling code here:
        try {
            ObjectOutputStream oos = new ObjectOutputStream(mySocket.getOutputStream());
            Character character = new Character("Donkey Kong", "donkeykong.png");
            oos.writeObject(new ObjectWrapper(ObjectWrapper.SEND_CHARACTER, character));
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDonkeyKongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBowser;
    private javax.swing.JButton btnDaisy;
    private javax.swing.JButton btnDonkeyKong;
    private javax.swing.JButton btnMario;
    private javax.swing.JButton btnPeach;
    private javax.swing.JButton btnToad;
    private javax.swing.JButton btnToadette;
    private javax.swing.JButton btnYoshi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
