/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ClientCtr;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.ObjectWrapper;
import model.User;
import model.UserStat;

/**
 *
 * @author hoang
 */
public class RankFrm extends javax.swing.JPanel {
    private ClientCtr myControl;
    private ArrayList<UserStat> listUserStat;
    /**
     * Creates new form RankFrm
     */
    public RankFrm(ClientCtr control) {
        initComponents();
        myControl = control;
        listUserStat = new ArrayList<UserStat>();
        
        tblResult.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int column = tblResult.getColumnModel().getColumnIndexAtX(e.getX()); // get the coloum of the button
                int row = e.getY() / tblResult.getRowHeight(); // get the row of the button
 
                // *Checking the row or column is valid or not
                if (row < tblResult.getRowCount() && row >= 0 && column < tblResult.getColumnCount() && column >= 0) {
                    UserStat us = listUserStat.get(row);
                    if(us.getId() == myControl.getMyUser().getId()) return;
                    User user = new User(us.getEmail(),us.getPassword(), us.getName(),us.getGender(), us.getDateOfBirth(),us.getDescription());
                    user.setId(us.getId());
                    new DetailsFrm(myControl, user).setVisible(true);
                }
            }
        });
        
        myControl.sendData(new ObjectWrapper(ObjectWrapper.RANKING, myControl.getMyUser()));
        myControl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_RANKING, this));
    }
    
    private void setTable(){
        String[] columnNames = {"Rank", "Name", "Win rate", "Number of wins", "Status"};
        String[][] value = new String[listUserStat.size()][columnNames.length];
        for(int i=0; i<listUserStat.size(); i++){
            value[i][0] = i + 1 + "";
            value[i][1] = listUserStat.get(i).getName();
            value[i][2] = listUserStat.get(i).getWinRate() + "";
            value[i][3] = listUserStat.get(i).getWinNumber() + "";
            boolean online = false;
            for(User user: myControl.getListOnline())
                if(user.getId() == listUserStat.get(i).getId()) online = true;
            if(online) value[i][4] = "Online";
            else value[i][4] = "Offline";
        }
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
        @Override
            public boolean isCellEditable(int row, int column) {
                //unable to edit cells
                return false;
            }
        };
        tblResult.setModel(tableModel);
    }
    
    public void receivedDataProcessing(ObjectWrapper data) {
        if(data.getData() instanceof ArrayList<?>) {
            listUserStat = (ArrayList<UserStat>) data.getData();
            setTable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Ranking");

        tblResult.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Name", "Win rate", "Number of wins", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
}
