/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ClientCtr;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Friend;
import model.ObjectWrapper;
import model.User;

/**
 *
 * @author hoang
 */
public class RequestFriendFrm extends javax.swing.JPanel {
    private ClientCtr myControl;
    private ArrayList<User> listRequest;
    /**
     * Creates new form ListFriendFrm
     */
    public RequestFriendFrm(ClientCtr control) {
        initComponents();
        myControl = control;
        listRequest = new ArrayList<User>();
        
        tblResult.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int column = tblResult.getColumnModel().getColumnIndexAtX(e.getX()); // get the coloum of the button
                int row = e.getY() / tblResult.getRowHeight(); // get the row of the button
 
                // *Checking the row or column is valid or not
                if (row < tblResult.getRowCount() && row >= 0 && column < tblResult.getColumnCount() && column >= 0) {
                    Object[] options = {"Accept", "Refuse", "Cancel"};
                    String gender = listRequest.get(row).getGender()==true?"Male":"Female";
                    String descripton = listRequest.get(row).getDescription()==null?"":listRequest.get(row).getDescription();
                    String inf = "Name: "+listRequest.get(row).getName()+
                            "\nDateOfBirth: "+listRequest.get(row).getDateOfBirth().toString()+
                            "\nGender: "+gender+
                            "\nEmail: "+listRequest.get(row).getEmail()
                            +"\nDescription: "+descripton;
                    int result = JOptionPane.showOptionDialog(null,
                        inf, "Request Friend",
                        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[2]);
                    if(result == JOptionPane.YES_OPTION){
                        User user1 = myControl.getMyUser();
                        User user2 = listRequest.get(row);
                        Friend friends = new Friend(user1,user2,Friend.IS_FRIEND);
                        myControl.sendData(new ObjectWrapper(ObjectWrapper.ADD_FRIEND, friends));
                    }else if(result == JOptionPane.NO_OPTION){
                        User user1 = myControl.getMyUser();
                        User user2 = listRequest.get(row);
                        Friend friends = new Friend(user1,user2);
                        myControl.sendData(new ObjectWrapper(ObjectWrapper.DELETE_FRIEND, friends));
                    } else
                        return;
                }
                listRequest.remove(row);
                tblResult.removeAll();
                setTable();
            }
        });
        
        myControl.sendData(new ObjectWrapper(ObjectWrapper.SEARCH_REQUEST_FRIEND, myControl.getMyUser()));
        myControl.getActiveFunction().add(new ObjectWrapper(ObjectWrapper.REPLY_SEARCH_REQUEST_FRIEND, this));
    }
    
    private void setTable(){
        String[] columnNames = {"Number", "Name", "Date of birth", "Gender", "Email"};
        String[][] value = new String[listRequest.size()][columnNames.length];
        for(int i=0; i<listRequest.size(); i++){
            value[i][0] = i + 1 + "";
            value[i][1] = listRequest.get(i).getName();
            value[i][2] = listRequest.get(i).getDateOfBirth().toString();
            value[i][3] = listRequest.get(i).getGender()==true?"Male":"Female";
            value[i][4] = listRequest.get(i).getEmail();
        }
        DefaultTableModel tableModel = new DefaultTableModel(value, columnNames) {
        @Override
            public boolean isCellEditable(int row, int column) {
                //unable to edit cells
                return false;
            }
        };
        tblResult.setModel(tableModel);
    }
    
    public void receivedDataProcessing(ObjectWrapper data) {
        if(data.getData() instanceof ArrayList<?>) {
            listRequest = (ArrayList<User>) data.getData();
            setTable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Request Friend");

        tblResult.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Date of birth", "Gender", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
}
